public class PrimitiveDataTypeDemo {
    public void printBasicDataType() {
        string batchName = 'TrueDream';
        integer totalCandidates = 25;
        boolean isAdminCompleted = true;
        system.debug (batchName + 'de' + 'totalCandidates ====>' + totalCandidates + 've batch is completed??' + isAdminCompleted);
        string batchDescription = batchName + 'is the best';
        System.debug(batchDescription);
    
    }

}

